config/routes.rb
Rails.application.routes.draw do
  root  "pages#home"

  get   "/about", to: "pages#about"

  get   "/signup", to: "users#new"

  get   "/login", to: "sessions#new"
  post  "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: [:new]
  resources :microposts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  default_scope { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    @micropost = current_user.microposts.new(
      content: params[:micropost][:content],
      picture: params[:micropost][:picture]
    )

    if @micropost.save
      redirect_to root_url
    else
      render "users/feed"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      @micropost = current_user.microposts.new
      @microposts = Micropost.all
      render "users/feed"
    end
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      flash[:success] = "Logged in."
      redirect_to user
    else
      flash[:danger] = "Invalid information."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password]
    )

    if @user.save
      redirect_to @user
    else
      render 'new' 
    end    
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url)
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>">
        <%= msg %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <hr>
    <div class="container">
        <span class="float-left text-muted">Awesomeblog Application &copy; FramgiaPH</span>

        <nav class="float-right">
            <%= link_to "Home", root_path, class: 'text-muted' %>
            <%= link_to "About", about_path, class: 'text-muted' %>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">awesomeblog</a>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to "About", about_path, class: 'nav-link' %>
                </li>

                <% if current_user %>
                    <li>
                        <%= link_to "Users", users_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <a><%= link_to current_user.name, user_path(current_user), class: 'nav-link' %></a>
                    </li>
                    <li>
                        <%= link_to "Logout", logout_path, method: :delete, class: 'nav-link' %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Signup", signup_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", login_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container pt-4">
      <%= render "layouts/flash_messages" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <h1>About awesomeblog</h1>
    <p>A twitter-style blogging site.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h1>Welcome to Awesome blog</h1>
    <p>This is the home page of awesome blog.</p>

    <p><small>This project is under Kredo and Framgia PH</small></p>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <div class="form-group">
        <%= f.text_area :content, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.file_field :picture, accept: 'image/jpeg, image/jpg, image/png' %>
    </div>

    <% if @micropost.errors.any? %>
        <div class="alert alert-danger">
            <ul class="m-0">
                <% @micropost.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.submit "Post", class: 'btn btn-success form-control' %>
<% end %>

app/views/shared/_micropost_item.html.erb
<div class="media p-3 border-top">
    <span class="mr-2"><%= gravatar_for(current_user) %></span>    

    <div class="media-body">
        <h4><%= link_to current_user.name, user_path(current_user) %></h4>
        <div><%= micropost.content %></div>

        <% if micropost.picture? %>
            <div>
                <%= image_tag micropost.picture.url, class: 'mw-100' %>
            </div>
        <% end %>

        <small class="text-muted">
            Posted <%= time_ago_in_words(micropost.created_at) %> ago
        </small>
    </div>
</div>

app/views/users/feed.html.erb
<div class="row">
    <div class="col-md-4">
        <h1><%= current_user.name %></h1>
        <%= link_to "View my profile", current_user %>

        <hr>

        <div>
            <h5>Share your thoughts</h5>
            <%= render "shared/micropost_form" %>
        </div>
    </div>
    <div class="col-md-8">
        <h3>Feed</h3>

        <% @microposts.each do |micropost| %>
            <%= render "shared/micropost_item", micropost: micropost  %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center">Users</h1>
<hr>

<div class="row">
    <% @users.each do |user| %>
        <div class="col-md-6">
            <div class="media">
                <div class="media-body">
                    <h4><%= link_to user.name, user %></h4>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="offset-md-3 col-md-6">
        <h1 class="text-center">Sign up</h1>

        <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
                <div class="alert alert-danger">
                    <ul class="m-0">
                        <% @user.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control"  %>
            </div>

            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>

            <%= f.submit "Create new account", class: "btn btn-primary form-control" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-4">
        <h1><%= @user.name %></h1>
        <p><%= @user.email %></p>
    </div>
    <div class="col-md-8">
        <h3>Microposts (<%= @user.microposts.count %>)</h3>

        <% if @user.microposts.any? %>
            <% @user.microposts.each do |micropost| %>
                <%= render "shared/micropost_item", micropost: micropost %>
            <% end %>
        <% else %>
            <hr>
            <p class="text-muted">Nothing to show.</p>
        <% end %>
    </div>
</div>